### PR TITLE
Create if,else if,else statement

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Padmanabh82** [comment]
wait i am working on it

**Comment by Padmanabh82** [comment]
See how it is

**Comment by Padmanabh82** [comment]
@shruti49 mam??

**Comment by Padmanabh82** [comment]
Ok stay online

**Comment by shruti49** [comment]
> Done @shruti49
Capture

**Comment by Padmanabh82** [comment]
@shruti49 please lable this for hactober fest

**Comment by Padmanabh82** [comment]
@shruti49 mama please lable this for hactober-fest

**Pull request merged**
